// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mengelbart/moqtransport (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -typed -write_package_comment=false -package moqtransport -self_package github.com/mengelbart/moqtransport -destination mock_handler_test.go github.com/mengelbart/moqtransport Handler
//

package moqtransport

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleGoAway mocks base method.
func (m *MockHandler) HandleGoAway(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGoAway", arg0)
}

// HandleGoAway indicates an expected call of HandleGoAway.
func (mr *MockHandlerMockRecorder) HandleGoAway(arg0 any) *MockHandlerHandleGoAwayCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGoAway", reflect.TypeOf((*MockHandler)(nil).HandleGoAway), arg0)
	return &MockHandlerHandleGoAwayCall{Call: call}
}

// MockHandlerHandleGoAwayCall wrap *gomock.Call
type MockHandlerHandleGoAwayCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlerHandleGoAwayCall) Return() *MockHandlerHandleGoAwayCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlerHandleGoAwayCall) Do(f func(string)) *MockHandlerHandleGoAwayCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlerHandleGoAwayCall) DoAndReturn(f func(string)) *MockHandlerHandleGoAwayCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HandleSubscribe mocks base method.
func (m *MockHandler) HandleSubscribe(arg0 *IncomingSubscribeRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSubscribe", arg0)
}

// HandleSubscribe indicates an expected call of HandleSubscribe.
func (mr *MockHandlerMockRecorder) HandleSubscribe(arg0 any) *MockHandlerHandleSubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSubscribe", reflect.TypeOf((*MockHandler)(nil).HandleSubscribe), arg0)
	return &MockHandlerHandleSubscribeCall{Call: call}
}

// MockHandlerHandleSubscribeCall wrap *gomock.Call
type MockHandlerHandleSubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandlerHandleSubscribeCall) Return() *MockHandlerHandleSubscribeCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandlerHandleSubscribeCall) Do(f func(*IncomingSubscribeRequest)) *MockHandlerHandleSubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandlerHandleSubscribeCall) DoAndReturn(f func(*IncomingSubscribeRequest)) *MockHandlerHandleSubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
