// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mengelbart/moqtransport (interfaces: ControlMessageParserI)
//
// Generated by this command:
//
//	mockgen -build_flags=-tags=gomock -package moqtransport -self_package github.com/mengelbart/moqtransport -destination mock_control_message_parser_internal_test.go github.com/mengelbart/moqtransport ControlMessageParserI
//

// Package moqtransport is a generated GoMock package.
package moqtransport

import (
	reflect "reflect"

	wire "github.com/mengelbart/moqtransport/internal/wire"
	gomock "go.uber.org/mock/gomock"
)

// MockControlMessageParserI is a mock of ControlMessageParserI interface.
type MockControlMessageParserI struct {
	ctrl     *gomock.Controller
	recorder *MockControlMessageParserIMockRecorder
	isgomock struct{}
}

// MockControlMessageParserIMockRecorder is the mock recorder for MockControlMessageParserI.
type MockControlMessageParserIMockRecorder struct {
	mock *MockControlMessageParserI
}

// NewMockControlMessageParserI creates a new mock instance.
func NewMockControlMessageParserI(ctrl *gomock.Controller) *MockControlMessageParserI {
	mock := &MockControlMessageParserI{ctrl: ctrl}
	mock.recorder = &MockControlMessageParserIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControlMessageParserI) EXPECT() *MockControlMessageParserIMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockControlMessageParserI) Parse() (wire.ControlMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse")
	ret0, _ := ret[0].(wire.ControlMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockControlMessageParserIMockRecorder) Parse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockControlMessageParserI)(nil).Parse))
}
