// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mengelbart/moqtransport (interfaces: ControlMessageSender)
//
// Generated by this command:
//
//	mockgen -build_flags=-tags=gomock -package moqtransport -self_package github.com/mengelbart/moqtransport -destination mock_control_message_sender.go github.com/mengelbart/moqtransport ControlMessageSender
//

// Package moqtransport is a generated GoMock package.
package moqtransport

import (
	reflect "reflect"

	wire "github.com/mengelbart/moqtransport/internal/wire"
	gomock "go.uber.org/mock/gomock"
)

// MockControlMessageSender is a mock of ControlMessageSender interface.
type MockControlMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockControlMessageSenderMockRecorder
	isgomock struct{}
}

// MockControlMessageSenderMockRecorder is the mock recorder for MockControlMessageSender.
type MockControlMessageSenderMockRecorder struct {
	mock *MockControlMessageSender
}

// NewMockControlMessageSender creates a new mock instance.
func NewMockControlMessageSender(ctrl *gomock.Controller) *MockControlMessageSender {
	mock := &MockControlMessageSender{ctrl: ctrl}
	mock.recorder = &MockControlMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControlMessageSender) EXPECT() *MockControlMessageSenderMockRecorder {
	return m.recorder
}

// QueueControlMessage mocks base method.
func (m *MockControlMessageSender) QueueControlMessage(arg0 wire.ControlMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueControlMessage", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueControlMessage indicates an expected call of QueueControlMessage.
func (mr *MockControlMessageSenderMockRecorder) QueueControlMessage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueControlMessage", reflect.TypeOf((*MockControlMessageSender)(nil).QueueControlMessage), arg0)
}

// close mocks base method.
func (m *MockControlMessageSender) close(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "close", err)
}

// close indicates an expected call of close.
func (mr *MockControlMessageSenderMockRecorder) close(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "close", reflect.TypeOf((*MockControlMessageSender)(nil).close), err)
}
