// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *FetchObject) append_v18(buf []byte) []byte {
	if m.HasGroupIDDelta() {
		buf = varint.Append(buf, uint64(m.GroupIDDelta))
	}
	if m.explicitSubgroupID() {
		buf = varint.Append(buf, uint64(m.SubgroupID))
	}
	if m.HasObjectIDDelta() {
		buf = varint.Append(buf, uint64(m.ObjectIDDelta))
	}
	if m.HasPriority() {
		buf = append(buf, m.PublisherPriority)
	}
	if m.HasProperties() {
		PropertiesBuf := appendKeyValuePairs_v18(nil, m.Properties)
		buf = varint.Append(buf, uint64(len(PropertiesBuf)))
		buf = append(buf, PropertiesBuf...)
	}
	buf = varint.Append(buf, uint64(len(m.ObjectPayload)))
	buf = append(buf, m.ObjectPayload...)
	return buf
}

func (m *FetchObject) parse_v18(r messageReader) error {
	var err error

	if m.HasGroupIDDelta() {
		m.GroupIDDelta, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	if m.explicitSubgroupID() {
		m.SubgroupID, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	if m.HasObjectIDDelta() {
		m.ObjectIDDelta, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	if m.HasPriority() {
		m.PublisherPriority, err = r.ReadByte()
		if err != nil {
			return err
		}
	}

	if m.HasProperties() {
		m.Properties, err = parseKeyValuePairsTLV_v18(r)
		if err != nil {
			return err
		}
	}

	var ObjectPayloadLength uint64
	ObjectPayloadLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.ObjectPayload, err = readBytes(r, ObjectPayloadLength)
	if err != nil {
		return err
	}

	return nil
}
