// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *Fetch) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	buf = varint.Append(buf, uint64(m.FetchType))
	if m.isStandalone() {
		buf = varint.Append(buf, uint64(len(m.TrackNamespace)))
		for _, v := range m.TrackNamespace {
			buf = varint.Append(buf, uint64(len(v)))
			buf = append(buf, v...)
		}
	}
	if m.isStandalone() {
		buf = varint.Append(buf, uint64(len(m.TrackName)))
		buf = append(buf, m.TrackName...)
	}
	if m.isStandalone() {
		buf = m.StartLocation.append_v18(buf)
	}
	if m.isStandalone() {
		buf = m.EndLocation.append_v18(buf)
	}
	if m.isJoining() {
		buf = varint.Append(buf, uint64(m.JoiningRequestID))
	}
	if m.isJoining() {
		buf = varint.Append(buf, uint64(m.JoiningStart))
	}
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	buf = appendKeyValuePairs_v18(buf, m.Parameters)
	return buf
}

func (m *Fetch) parse_v18(r messageReader) error {
	var err error

	m.RequestID, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.FetchType, err = varint.Read(r)
	if err != nil {
		return err
	}

	if m.isStandalone() {
		var numTrackNamespace uint64
		numTrackNamespace, err = varint.Read(r)
		if err != nil {
			return err
		}

		m.TrackNamespace = make([][]byte, 0)
		for range numTrackNamespace {
			var length uint64
			length, err = varint.Read(r)
			if err != nil {
				return err
			}

			var value []byte
			value, err = readBytes(r, length)
			if err != nil {
				return err
			}
			m.TrackNamespace = append(m.TrackNamespace, value)
		}
	}

	if m.isStandalone() {
		var TrackNameLength uint64
		TrackNameLength, err = varint.Read(r)
		if err != nil {
			return err
		}

		m.TrackName, err = readBytes(r, TrackNameLength)
		if err != nil {
			return err
		}
	}

	if m.isStandalone() {
		if err = m.StartLocation.parse_v18(r); err != nil {
			return err
		}
	}

	if m.isStandalone() {
		if err = m.EndLocation.parse_v18(r); err != nil {
			return err
		}
	}

	if m.isJoining() {
		m.JoiningRequestID, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	if m.isJoining() {
		m.JoiningStart, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	m.Parameters, err = parseKeyValuePairsCount_v18(r)
	if err != nil {
		return err
	}

	return nil
}
