// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *FetchHeader) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	return buf
}

func (m *FetchHeader) parse_v18(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	return nil
}
