// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import (
	"errors"

	"github.com/mengelbart/moqtransport/varint"
)

func (m *FetchOk) append_v18(buf []byte) []byte {
	if m.EndOfTrack {
		buf = append(buf, byte(1))
	} else {
		buf = append(buf, byte(0))
	}
	buf = m.EndLocation.append_v18(buf)
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	buf = appendKeyValuePairs_v18(buf, m.Parameters)
	buf = appendKeyValuePairs_v18(buf, m.Properties)
	return buf
}

func (m *FetchOk) parse_v18(r messageReader) error {
	var err error

	var EndOfTrackByte byte
	EndOfTrackByte, err = r.ReadByte()
	if err != nil {
		return err
	}
	if EndOfTrackByte > 1 {
		return errors.New("invalid bool flag value")
	}
	m.EndOfTrack = EndOfTrackByte > 0

	if err = m.EndLocation.parse_v18(r); err != nil {
		return err
	}

	m.Parameters, err = parseKeyValuePairsCount_v18(r)
	if err != nil {
		return err
	}

	m.Properties, err = parseKeyValuePairsRemaining_v18(r)
	if err != nil {
		return err
	}

	return nil
}
