// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import (
	"errors"
	"io"

	"github.com/mengelbart/moqtransport/varint"
)

func (m *FetchOk) append_v18(buf []byte) []byte {
	if m.EndOfTrack {
		buf = append(buf, byte(1))
	} else {
		buf = append(buf, byte(0))
	}
	buf = m.EndLocation.append(buf)
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = varint.Append(buf, uint64(v.Type))
		if v.Type%2 == 0 {
			buf = varint.Append(buf, uint64(v.Varint))
		} else {
			buf = varint.Append(buf, uint64(len(v.Bytes)))
			buf = append(buf, v.Bytes...)
		}
	}
	buf = varint.Append(buf, uint64(len(m.Properties)))
	for _, v := range m.Properties {
		buf = varint.Append(buf, uint64(v.Type))
		if v.Type%2 == 0 {
			buf = varint.Append(buf, uint64(v.Varint))
		} else {
			buf = varint.Append(buf, uint64(len(v.Bytes)))
			buf = append(buf, v.Bytes...)
		}
	}
	return buf
}

func (m *FetchOk) parse_v18(data []byte) error {
	var err error
	var n int

	if len(data) < 1 {
		return io.ErrUnexpectedEOF
	}
	if data[0] > 1 {
		return errors.New("invalid bool flag value")
	}
	m.EndOfTrack = data[0] > 0
	data = data[1:]

	n, err = m.EndLocation.parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var numParameters uint64
	numParameters, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.Parameters = make([]KeyValuePair, numParameters)
	for i := range numParameters {
		typ, n, err := varint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if typ%2 == 0 {
			val, n, err := varint.Parse(data)
			if err != nil {
				return err
			}
			m.Parameters[i] = KeyValuePair{
				Type:   typ,
				Varint: val,
			}
			data = data[n:]
		} else {
			length, n, err := varint.Parse(data)
			if err != nil {
				return err
			}
			data = data[n:]
			if len(data) < int(length) {
				return io.ErrUnexpectedEOF
			}
			m.Parameters[i] = KeyValuePair{
				Type:  typ,
				Bytes: data[:length],
			}
			data = data[length:]
		}
	}

	var numProperties uint64
	numProperties, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.Properties = make([]KeyValuePair, numProperties)
	for i := range numProperties {
		typ, n, err := varint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if typ%2 == 0 {
			val, n, err := varint.Parse(data)
			if err != nil {
				return err
			}
			m.Properties[i] = KeyValuePair{
				Type:   typ,
				Varint: val,
			}
			data = data[n:]
		} else {
			length, n, err := varint.Parse(data)
			if err != nil {
				return err
			}
			data = data[n:]
			if len(data) < int(length) {
				return io.ErrUnexpectedEOF
			}
			m.Properties[i] = KeyValuePair{
				Type:  typ,
				Bytes: data[:length],
			}
			data = data[length:]
		}
	}

	return nil
}
