// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *FetchHeader) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	return buf
}

func (m *FetchHeader) parse_v18(r messageReader) error {
	var err error

	m.RequestID, err = varint.Read(r)
	if err != nil {
		return err
	}

	return nil
}
