// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import (
	"io"

	"github.com/mengelbart/moqtransport/varint"
)

func (m *GoAwayReq) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(len(m.NewSessionURI)))
	buf = append(buf, []byte(m.NewSessionURI)...)
	buf = varint.Append(buf, uint64(m.Timeout))
	return buf
}

func (m *GoAwayReq) parse_v18(data []byte) error {
	var err error
	var n int

	var NewSessionURILength uint64
	NewSessionURILength, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) < int(NewSessionURILength) {
		return io.ErrUnexpectedEOF
	}
	m.NewSessionURI = string(data[:NewSessionURILength])
	data = data[NewSessionURILength:]

	m.Timeout, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	return nil
}
