// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *GoAwayReq) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(len(m.NewSessionURI)))
	buf = append(buf, []byte(m.NewSessionURI)...)
	buf = varint.Append(buf, uint64(m.Timeout))
	return buf
}

func (m *GoAwayReq) parse_v18(r messageReader) error {
	var err error

	var NewSessionURILength uint64
	NewSessionURILength, err = varint.Read(r)
	if err != nil {
		return err
	}

	var NewSessionURIBytes []byte
	NewSessionURIBytes, err = readBytes(r, NewSessionURILength)
	if err != nil {
		return err
	}
	m.NewSessionURI = string(NewSessionURIBytes)

	m.Timeout, err = varint.Read(r)
	if err != nil {
		return err
	}

	return nil
}
