// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *KeyValuePair) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.Type))
	if m.hasBytes() {
		buf = varint.Append(buf, uint64(len(m.Bytes)))
		buf = append(buf, m.Bytes...)
	}
	if !m.hasBytes() {
		buf = varint.Append(buf, uint64(m.Varint))
	}
	return buf
}

func (m *KeyValuePair) parse_v18(r messageReader) error {
	var err error

	m.Type, err = varint.Read(r)
	if err != nil {
		return err
	}

	if m.hasBytes() {
		var BytesLength uint64
		BytesLength, err = varint.Read(r)
		if err != nil {
			return err
		}

		m.Bytes, err = readBytes(r, BytesLength)
		if err != nil {
			return err
		}
	}

	if !m.hasBytes() {
		m.Varint, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	return nil
}
