// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *Location) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.Group))
	buf = varint.Append(buf, uint64(m.Object))
	return buf
}

func (m *Location) parse_v18(r messageReader) error {
	var err error

	m.Group, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.Object, err = varint.Read(r)
	if err != nil {
		return err
	}

	return nil
}
