// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import (
	"io"

	"github.com/mengelbart/moqtransport/varint"
)

func (m *NamespaceDone) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(len(m.TrackNamespaceSuffix)))
	for _, v := range m.TrackNamespaceSuffix {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	return buf
}

func (m *NamespaceDone) parse_v18(data []byte) error {
	var err error
	var n int

	var numTrackNamespaceSuffix uint64
	numTrackNamespaceSuffix, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.TrackNamespaceSuffix = make([][]byte, 0)
	for range numTrackNamespaceSuffix {
		var length uint64
		length, n, err = varint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if len(data) < int(length) {
			return io.ErrUnexpectedEOF
		}
		m.TrackNamespaceSuffix = append(m.TrackNamespaceSuffix, data[:length])
		data = data[length:]
	}

	return nil
}
