// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *ObjectDatagram) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.TrackAlias))
	buf = varint.Append(buf, uint64(m.GroupID))
	if !m.ZeroObjectID() {
		buf = varint.Append(buf, uint64(m.ObjectID))
	}
	if !m.DefaultPriority() {
		buf = append(buf, m.PublisherPriority)
	}
	if m.HasProperties() {
		buf = varint.Append(buf, uint64(len(m.Properties)))
		for _, v := range m.Properties {
			buf = v.append_v18(buf)
		}
	}
	if m.Status() {
		buf = varint.Append(buf, uint64(m.ObjectStatus))
	}
	if !m.Status() {
		buf = append(buf, m.ObjectPayload...)
	}
	return buf
}

func (m *ObjectDatagram) parse_v18(r messageReader) error {
	var err error

	m.TrackAlias, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.GroupID, err = varint.Read(r)
	if err != nil {
		return err
	}

	if !m.ZeroObjectID() {
		m.ObjectID, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	if !m.DefaultPriority() {
		m.PublisherPriority, err = r.ReadByte()
		if err != nil {
			return err
		}
	}

	if m.HasProperties() {
		var numProperties uint64
		numProperties, err = varint.Read(r)
		if err != nil {
			return err
		}

		m.Properties = make([]KeyValuePair, 0)
		for range numProperties {
			var value KeyValuePair
			if err = value.parse_v18(r); err != nil {
				return err
			}
			m.Properties = append(m.Properties, value)
		}
	}

	if m.Status() {
		m.ObjectStatus, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	if !m.Status() {
		m.ObjectPayload, err = readRemaining(r)
		if err != nil {
			return err
		}
	}

	return nil
}
