// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *ObjectStream) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.ObjectIDDelta))
	if m.HasProperties() {
		var PropertiesBuf []byte
		for _, v := range m.Properties {
			PropertiesBuf = v.append_v18(PropertiesBuf)
		}
		buf = varint.Append(buf, uint64(len(PropertiesBuf)))
		buf = append(buf, PropertiesBuf...)
	}
	buf = varint.Append(buf, uint64(len(m.ObjectPayload)))
	buf = append(buf, m.ObjectPayload...)
	if m.EmptyPayload() {
		buf = varint.Append(buf, uint64(m.ObjectStatus))
	}
	return buf
}

func (m *ObjectStream) parse_v18(r messageReader) error {
	var err error

	m.ObjectIDDelta, err = varint.Read(r)
	if err != nil {
		return err
	}

	if m.HasProperties() {
		var PropertiesReader *boundedReader
		PropertiesReader, err = tlvReader(r)
		if err != nil {
			return err
		}

		m.Properties = make([]KeyValuePair, 0)
		for PropertiesReader.remaining() > 0 {
			var value KeyValuePair
			if err = value.parse_v18(PropertiesReader); err != nil {
				return err
			}
			m.Properties = append(m.Properties, value)
		}
	}

	var ObjectPayloadLength uint64
	ObjectPayloadLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.ObjectPayload, err = readBytes(r, ObjectPayloadLength)
	if err != nil {
		return err
	}

	if m.EmptyPayload() {
		m.ObjectStatus, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	return nil
}
