// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

func (m *Padding) append_v18(buf []byte) []byte {
	return buf
}

func (m *Padding) parse_v18(r messageReader) error {
	return nil
}
