// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *PublishDone) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.StatusCode))
	buf = varint.Append(buf, uint64(m.StreamCount))
	buf = varint.Append(buf, uint64(len(m.ErrorReason)))
	buf = append(buf, []byte(m.ErrorReason)...)
	return buf
}

func (m *PublishDone) parse_v18(r messageReader) error {
	var err error

	m.StatusCode, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.StreamCount, err = varint.Read(r)
	if err != nil {
		return err
	}

	var ErrorReasonLength uint64
	ErrorReasonLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	var ErrorReasonBytes []byte
	ErrorReasonBytes, err = readBytes(r, ErrorReasonLength)
	if err != nil {
		return err
	}
	m.ErrorReason = string(ErrorReasonBytes)

	return nil
}
