// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *Publish) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	buf = varint.Append(buf, uint64(len(m.TrackNamespace)))
	for _, v := range m.TrackNamespace {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = varint.Append(buf, uint64(len(m.TrackName)))
	buf = append(buf, m.TrackName...)
	buf = varint.Append(buf, uint64(m.TrackAlias))
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = v.append_v18(buf)
	}
	for _, v := range m.Properties {
		buf = v.append_v18(buf)
	}
	return buf
}

func (m *Publish) parse_v18(r messageReader) error {
	var err error

	m.RequestID, err = varint.Read(r)
	if err != nil {
		return err
	}

	var numTrackNamespace uint64
	numTrackNamespace, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackNamespace = make([][]byte, 0)
	for range numTrackNamespace {
		var length uint64
		length, err = varint.Read(r)
		if err != nil {
			return err
		}

		var value []byte
		value, err = readBytes(r, length)
		if err != nil {
			return err
		}
		m.TrackNamespace = append(m.TrackNamespace, value)
	}

	var TrackNameLength uint64
	TrackNameLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackName, err = readBytes(r, TrackNameLength)
	if err != nil {
		return err
	}

	m.TrackAlias, err = varint.Read(r)
	if err != nil {
		return err
	}

	var numParameters uint64
	numParameters, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.Parameters = make([]KeyValuePair, 0)
	for range numParameters {
		var value KeyValuePair
		if err = value.parse_v18(r); err != nil {
			return err
		}
		m.Parameters = append(m.Parameters, value)
	}

	if r.remaining() < 0 {
		return errNoMessageLength
	}
	m.Properties = make([]KeyValuePair, 0)
	for r.remaining() > 0 {
		var value KeyValuePair
		if err = value.parse_v18(r); err != nil {
			return err
		}
		m.Properties = append(m.Properties, value)
	}

	return nil
}
