// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *PublishOk) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	buf = appendKeyValuePairs_v18(buf, m.Parameters)
	buf = appendKeyValuePairs_v18(buf, m.Properties)
	return buf
}

func (m *PublishOk) parse_v18(r messageReader) error {
	var err error

	m.Parameters, err = parseKeyValuePairsCount_v18(r)
	if err != nil {
		return err
	}

	m.Properties, err = parseKeyValuePairsRemaining_v18(r)
	if err != nil {
		return err
	}

	return nil
}
