// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *PublishOk) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = v.append_v18(buf)
	}
	for _, v := range m.Properties {
		buf = v.append_v18(buf)
	}
	return buf
}

func (m *PublishOk) parse_v18(r messageReader) error {
	var err error

	var numParameters uint64
	numParameters, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.Parameters = make([]KeyValuePair, 0)
	for range numParameters {
		var value KeyValuePair
		if err = value.parse_v18(r); err != nil {
			return err
		}
		m.Parameters = append(m.Parameters, value)
	}

	if r.remaining() < 0 {
		return errNoMessageLength
	}
	m.Properties = make([]KeyValuePair, 0)
	for r.remaining() > 0 {
		var value KeyValuePair
		if err = value.parse_v18(r); err != nil {
			return err
		}
		m.Properties = append(m.Properties, value)
	}

	return nil
}
