// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *PublishBlocked) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(len(m.TrackNamespaceSuffix)))
	for _, v := range m.TrackNamespaceSuffix {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = varint.Append(buf, uint64(len(m.TrackName)))
	buf = append(buf, m.TrackName...)
	return buf
}

func (m *PublishBlocked) parse_v18(r messageReader) error {
	var err error

	var numTrackNamespaceSuffix uint64
	numTrackNamespaceSuffix, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackNamespaceSuffix = make([][]byte, 0)
	for range numTrackNamespaceSuffix {
		var length uint64
		length, err = varint.Read(r)
		if err != nil {
			return err
		}

		var value []byte
		value, err = readBytes(r, length)
		if err != nil {
			return err
		}
		m.TrackNamespaceSuffix = append(m.TrackNamespaceSuffix, value)
	}

	var TrackNameLength uint64
	TrackNameLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackName, err = readBytes(r, TrackNameLength)
	if err != nil {
		return err
	}

	return nil
}
