// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *Redirect) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(len(m.ConnectURI)))
	buf = append(buf, []byte(m.ConnectURI)...)
	buf = varint.Append(buf, uint64(len(m.TrackNamespace)))
	for _, v := range m.TrackNamespace {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = varint.Append(buf, uint64(len(m.TrackName)))
	buf = append(buf, m.TrackName...)
	return buf
}

func (m *Redirect) parse_v18(r messageReader) error {
	var err error

	var ConnectURILength uint64
	ConnectURILength, err = varint.Read(r)
	if err != nil {
		return err
	}

	var ConnectURIBytes []byte
	ConnectURIBytes, err = readBytes(r, ConnectURILength)
	if err != nil {
		return err
	}
	m.ConnectURI = string(ConnectURIBytes)

	var numTrackNamespace uint64
	numTrackNamespace, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackNamespace = make([][]byte, 0)
	for range numTrackNamespace {
		var length uint64
		length, err = varint.Read(r)
		if err != nil {
			return err
		}

		var value []byte
		value, err = readBytes(r, length)
		if err != nil {
			return err
		}
		m.TrackNamespace = append(m.TrackNamespace, value)
	}

	var TrackNameLength uint64
	TrackNameLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackName, err = readBytes(r, TrackNameLength)
	if err != nil {
		return err
	}

	return nil
}
