// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *RequestUpdate) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = v.append_v18(buf)
	}
	return buf
}

func (m *RequestUpdate) parse_v18(r messageReader) error {
	var err error

	m.RequestID, err = varint.Read(r)
	if err != nil {
		return err
	}

	var numParameters uint64
	numParameters, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.Parameters = make([]KeyValuePair, 0)
	for range numParameters {
		var value KeyValuePair
		if err = value.parse_v18(r); err != nil {
			return err
		}
		m.Parameters = append(m.Parameters, value)
	}

	return nil
}
