// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *RequestError) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.ErrorCode))
	buf = varint.Append(buf, uint64(m.RetryInterval))
	buf = varint.Append(buf, uint64(len(m.ErrorReason)))
	buf = append(buf, []byte(m.ErrorReason)...)
	return buf
}

func (m *RequestError) parse_v18(r messageReader) error {
	var err error

	m.ErrorCode, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.RetryInterval, err = varint.Read(r)
	if err != nil {
		return err
	}

	var ErrorReasonLength uint64
	ErrorReasonLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	var ErrorReasonBytes []byte
	ErrorReasonBytes, err = readBytes(r, ErrorReasonLength)
	if err != nil {
		return err
	}
	m.ErrorReason = string(ErrorReasonBytes)

	return nil
}
