// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

func (m *RequestOk) append_v18(buf []byte) []byte {
	buf = appendParameters_v18(buf, m.Parameters)
	buf = appendKeyValuePairs_v18(buf, m.Properties)
	return buf
}

func (m *RequestOk) parse_v18(r messageReader) error {
	var err error

	m.Parameters, err = parseParameters_v18(r)
	if err != nil {
		return err
	}

	m.Properties, err = parseKeyValuePairsRemaining_v18(r)
	if err != nil {
		return err
	}

	return nil
}
