// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

func (m *Setup) append_v18(buf []byte) []byte {
	buf = appendKeyValuePairs_v18(buf, m.Options)
	return buf
}

func (m *Setup) parse_v18(r messageReader) error {
	var err error

	m.Options, err = parseKeyValuePairsRemaining_v18(r)
	if err != nil {
		return err
	}

	return nil
}
