// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *SubgroupObject) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.ObjectIDDelta))
	if m.HasProperties() {
		PropertiesBuf := appendKeyValuePairs_v18(nil, m.Properties)
		buf = varint.Append(buf, uint64(len(PropertiesBuf)))
		buf = append(buf, PropertiesBuf...)
	}
	buf = varint.Append(buf, uint64(len(m.ObjectPayload)))
	buf = append(buf, m.ObjectPayload...)
	if m.EmptyPayload() {
		buf = varint.Append(buf, uint64(m.ObjectStatus))
	}
	return buf
}

func (m *SubgroupObject) parse_v18(r messageReader) error {
	var err error

	m.ObjectIDDelta, err = varint.Read(r)
	if err != nil {
		return err
	}

	if m.HasProperties() {
		m.Properties, err = parseKeyValuePairsTLV_v18(r)
		if err != nil {
			return err
		}
	}

	var ObjectPayloadLength uint64
	ObjectPayloadLength, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.ObjectPayload, err = readBytes(r, ObjectPayloadLength)
	if err != nil {
		return err
	}

	if m.EmptyPayload() {
		m.ObjectStatus, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	return nil
}
