// Code generated by \"protogen -dir ./internal/wire/\"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *SubgroupHeader) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.TrackAlias))
	buf = varint.Append(buf, uint64(m.GroupID))
	if m.explicitSubgroupID() {
		buf = varint.Append(buf, uint64(m.SubgroupID))
	}
	if !m.DefaultPriority() {
		buf = append(buf, m.PublisherPriority)
	}
	return buf
}

func (m *SubgroupHeader) parse_v18(r messageReader) error {
	var err error

	m.TrackAlias, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.GroupID, err = varint.Read(r)
	if err != nil {
		return err
	}

	if m.explicitSubgroupID() {
		m.SubgroupID, err = varint.Read(r)
		if err != nil {
			return err
		}
	}

	if !m.DefaultPriority() {
		m.PublisherPriority, err = r.ReadByte()
		if err != nil {
			return err
		}
	}

	return nil
}
