// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *SubscribeNamespace) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	buf = varint.Append(buf, uint64(len(m.TrackNamespacePrefix)))
	for _, v := range m.TrackNamespacePrefix {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = v.append_v18(buf)
	}
	return buf
}

func (m *SubscribeNamespace) parse_v18(r messageReader) error {
	var err error

	m.RequestID, err = varint.Read(r)
	if err != nil {
		return err
	}

	var numTrackNamespacePrefix uint64
	numTrackNamespacePrefix, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackNamespacePrefix = make([][]byte, 0)
	for range numTrackNamespacePrefix {
		var length uint64
		length, err = varint.Read(r)
		if err != nil {
			return err
		}

		var value []byte
		value, err = readBytes(r, length)
		if err != nil {
			return err
		}
		m.TrackNamespacePrefix = append(m.TrackNamespacePrefix, value)
	}

	var numParameters uint64
	numParameters, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.Parameters = make([]KeyValuePair, 0)
	for range numParameters {
		var value KeyValuePair
		if err = value.parse_v18(r); err != nil {
			return err
		}
		m.Parameters = append(m.Parameters, value)
	}

	return nil
}
