// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire

import (
	"io"

	"github.com/mengelbart/moqtransport/varint"
)

func (m *Subscribe) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	buf = varint.Append(buf, uint64(len(m.TrackNamespace)))
	for _, v := range m.TrackNamespace {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = varint.Append(buf, uint64(len(m.TrackName)))
	buf = append(buf, m.TrackName...)
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = varint.Append(buf, uint64(v.Type))
		if v.Type%2 == 0 {
			buf = varint.Append(buf, uint64(v.Varint))
		} else {
			buf = varint.Append(buf, uint64(len(v.Bytes)))
			buf = append(buf, v.Bytes...)
		}
	}
	return buf
}

func (m *Subscribe) parse_v18(data []byte) error {
	var err error
	var n int

	m.RequestID, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	var numTrackNamespace uint64
	numTrackNamespace, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.TrackNamespace = make([][]byte, numTrackNamespace)
	for i := range numTrackNamespace {
		var length uint64
		length, n, err = varint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if len(data) < int(length) {
			return io.ErrUnexpectedEOF
		}
		m.TrackNamespace[i] = data[:length]
		data = data[length:]
	}

	var TrackNameLength uint64
	TrackNameLength, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	if len(data) < int(TrackNameLength) {
		return io.ErrUnexpectedEOF
	}
	m.TrackName = data[:TrackNameLength]
	data = data[TrackNameLength:]

	var numParameters uint64
	numParameters, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.Parameters = make([]KeyValuePair, numParameters)
	for i := range numParameters {
		typ, n, err := varint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if typ%2 == 0 {
			val, n, err := varint.Parse(data)
			if err != nil {
				return err
			}
			m.Parameters[i] = KeyValuePair{
				Type:   typ,
				Varint: val,
			}
			data = data[n:]
		} else {
			length, n, err := varint.Parse(data)
			if err != nil {
				return err
			}
			data = data[n:]
			if len(data) < int(length) {
				return io.ErrUnexpectedEOF
			}
			m.Parameters[i] = KeyValuePair{
				Type:  typ,
				Bytes: data[:length],
			}
			data = data[length:]
		}
	}

	return nil
}
