// Code generated by "wiregen -dir ./internal/wire/"; DO NOT EDIT.

package wire

import "github.com/mengelbart/moqtransport/varint"

func (m *SubscribeTracks) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.RequestID))
	buf = varint.Append(buf, uint64(len(m.TrackNamespacePrefix)))
	for _, v := range m.TrackNamespacePrefix {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	buf = varint.Append(buf, uint64(len(m.Parameters)))
	buf = appendKeyValuePairs_v18(buf, m.Parameters)
	return buf
}

func (m *SubscribeTracks) parse_v18(r messageReader) error {
	var err error

	m.RequestID, err = varint.Read(r)
	if err != nil {
		return err
	}

	var numTrackNamespacePrefix uint64
	numTrackNamespacePrefix, err = varint.Read(r)
	if err != nil {
		return err
	}

	m.TrackNamespacePrefix = make([][]byte, 0)
	for range numTrackNamespacePrefix {
		var length uint64
		length, err = varint.Read(r)
		if err != nil {
			return err
		}

		var value []byte
		value, err = readBytes(r, length)
		if err != nil {
			return err
		}
		m.TrackNamespacePrefix = append(m.TrackNamespacePrefix, value)
	}

	m.Parameters, err = parseKeyValuePairsCount_v18(r)
	if err != nil {
		return err
	}

	return nil
}
