// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/quic-go/quic-go/quicvarint"
)

func (m *Namespace) append_v18(buf []byte) []byte {
	buf = quicvarint.Append(buf, uint64(len(m.TrackNamespaceSuffix)))
	for _, v := range m.TrackNamespaceSuffix {
		buf = quicvarint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
	return buf
}

func (m *Namespace) parse_v18(data []byte) error {
	var err error
	var n int

	var numTrackNamespaceSuffix uint64
	numTrackNamespaceSuffix, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.TrackNamespaceSuffix = make([][]byte, numTrackNamespaceSuffix)
	for i := range numTrackNamespaceSuffix {
		var length uint64
		length, n, err = quicvarint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if len(data) < int(length) {
			return io.ErrUnexpectedEOF
		}
		m.TrackNamespaceSuffix[i] = data[:length]
		data = data[length:]
	}

	return nil
}
