// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

func (m *Padding) append_v18(buf []byte) []byte {
	return buf
}

func (m *Padding) parse_v18(data []byte) error {

	return nil
}
