// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import (
	"io"

	"github.com/quic-go/quic-go/quicvarint"
)

func (m *PublishOk) append_v18(buf []byte) []byte {
	buf = quicvarint.Append(buf, uint64(len(m.Parameters)))
	for _, v := range m.Parameters {
		buf = quicvarint.Append(buf, uint64(v.Type))
		if v.Type%2 == 0 {
			buf = quicvarint.Append(buf, uint64(v.Varint))
		} else {
			buf = quicvarint.Append(buf, uint64(len(v.Bytes)))
			buf = append(buf, v.Bytes...)
		}
	}
	buf = quicvarint.Append(buf, uint64(len(m.Properties)))
	for _, v := range m.Properties {
		buf = quicvarint.Append(buf, uint64(v.Type))
		if v.Type%2 == 0 {
			buf = quicvarint.Append(buf, uint64(v.Varint))
		} else {
			buf = quicvarint.Append(buf, uint64(len(v.Bytes)))
			buf = append(buf, v.Bytes...)
		}
	}
	return buf
}

func (m *PublishOk) parse_v18(data []byte) error {
	var err error
	var n int

	var numParameters uint64
	numParameters, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.Parameters = make([]KeyValuePair, numParameters)
	for i := range numParameters {
		typ, n, err := quicvarint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if typ%2 == 0 {
			val, n, err := quicvarint.Parse(data)
			if err != nil {
				return err
			}
			m.Parameters[i] = KeyValuePair{
				Type:   typ,
				Varint: val,
			}
			data = data[n:]
		} else {
			length, n, err := quicvarint.Parse(data)
			if err != nil {
				return err
			}
			data = data[n:]
			if len(data) < int(length) {
				return io.ErrUnexpectedEOF
			}
			m.Parameters[i] = KeyValuePair{
				Type:  typ,
				Bytes: data[:length],
			}
			data = data[length:]
		}
	}

	var numProperties uint64
	numProperties, n, err = quicvarint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.Properties = make([]KeyValuePair, numProperties)
	for i := range numProperties {
		typ, n, err := quicvarint.Parse(data)
		if err != nil {
			return err
		}
		data = data[n:]

		if typ%2 == 0 {
			val, n, err := quicvarint.Parse(data)
			if err != nil {
				return err
			}
			m.Properties[i] = KeyValuePair{
				Type:   typ,
				Varint: val,
			}
			data = data[n:]
		} else {
			length, n, err := quicvarint.Parse(data)
			if err != nil {
				return err
			}
			data = data[n:]
			if len(data) < int(length) {
				return io.ErrUnexpectedEOF
			}
			m.Properties[i] = KeyValuePair{
				Type:  typ,
				Bytes: data[:length],
			}
			data = data[length:]
		}
	}

	return nil
}
