// Code generated by \"protogen -dir ./internal/wire2/\"; DO NOT EDIT.

package wire2

import "github.com/mengelbart/moqtransport/varint"

func (m *SubgroupHeader) append_v18(buf []byte) []byte {
	buf = varint.Append(buf, uint64(m.TrackAlias))
	buf = varint.Append(buf, uint64(m.GroupID))
	return buf
}

func (m *SubgroupHeader) parse_v18(data []byte) error {
	var err error
	var n int

	m.TrackAlias, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	m.GroupID, n, err = varint.Parse(data)
	if err != nil {
		return err
	}
	data = data[n:]

	return nil
}
