package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"strings"
	"text/template"

	"golang.org/x/tools/imports"
)

var errInvalidPackage = errors.New("invalid package name")

type unknownProtoTypeErr string

func (e unknownProtoTypeErr) Error() string {
	return fmt.Sprintf("unknown proto type: %s", string(e))
}

type unknownProtoModifierErr string

func (e unknownProtoModifierErr) Error() string {
	return fmt.Sprintf("unknown proto modifier: %s", string(e))
}

// field is one serialized struct field: a wire kind, and optionally a
// predicate method on the message deciding whether the field is present.
type field struct {
	name      string
	elem      string
	kind      string
	condition string
	negate    bool
}

// parseField reads the proto tag, a wire kind followed by comma separated
// modifiers. The only modifier is if=Predicate, or if=!Predicate, naming a
// method on the message.
func parseField(name, tag, elem string) (field, error) {
	parts := strings.Split(tag, ",")
	out := field{
		name: name,
		elem: elem,
		kind: parts[0],
	}
	for _, mod := range parts[1:] {
		condition, ok := strings.CutPrefix(mod, "if=")
		if !ok {
			return out, unknownProtoModifierErr(mod)
		}
		out.condition, out.negate = strings.CutPrefix(condition, "!")
	}
	return out, nil
}

func (f field) data(suffix string) map[string]string {
	return map[string]string{
		"Field":  f.name,
		"Elem":   f.elem,
		"Suffix": suffix,
	}
}

// emit writes the fragment for one field, wrapped in the field's condition.
func (g *generator) emit(templates map[string]*template.Template, f field) error {
	tmpl, ok := templates[f.kind]
	if !ok {
		return unknownProtoTypeErr(f.kind)
	}
	if f.condition != "" {
		negate := ""
		if f.negate {
			negate = "!"
		}
		g.printf("if %sm.%s() {\n", negate, f.condition)
	}
	if err := tmpl.Execute(g, f.data(g.methodSuffix)); err != nil {
		return err
	}
	if f.condition != "" {
		g.printf("}\n")
	}
	return nil
}

type generator struct {
	pkg          string
	methodSuffix string

	buf bytes.Buffer
}

var appenderTemplates = map[string]*template.Template{
	"quicvarint": template.Must(template.New("quicvarint_append").Parse(`	buf = quicvarint.Append(buf, uint64(m.{{ .Field }}))
`)),

	"varint": template.Must(template.New("varint_append").Parse(`	buf = varint.Append(buf, uint64(m.{{ .Field }}))
`)),

	"tlv_bytes": template.Must(template.New("tlv_bytes_append").Parse(`	buf = varint.Append(buf, uint64(len(m.{{ .Field }})))
	buf = append(buf, m.{{ .Field }}...)
`)),

	"tlv_string": template.Must(template.New("tlv_bytes_append").Parse(`	buf = varint.Append(buf, uint64(len(m.{{ .Field }})))
	buf = append(buf, []byte(m.{{ .Field }})...)
`)),

	"ntlv_bytes": template.Must(template.New("ntlv_bytes_append").Parse(`	buf = varint.Append(buf, uint64(len(m.{{ .Field }})))
	for _, v := range m.{{ .Field }} {
		buf = varint.Append(buf, uint64(len(v)))
		buf = append(buf, v...)
	}
`)),

	"message_list": template.Must(template.New("message_list_append").Parse(`	buf = varint.Append(buf, uint64(len(m.{{ .Field }})))
	for _, v := range m.{{ .Field }} {
		buf = v.append{{ .Suffix }}(buf)
	}
`)),

	"tlv_message_list": template.Must(template.New("tlv_message_list_append").Parse(`	var {{ .Field }}Buf []byte
	for _, v := range m.{{ .Field }} {
		{{ .Field }}Buf = v.append{{ .Suffix }}({{ .Field }}Buf)
	}
	buf = varint.Append(buf, uint64(len({{ .Field }}Buf)))
	buf = append(buf, {{ .Field }}Buf...)
`)),

	"message_list_no_length": template.Must(template.New("message_list_no_length_append").Parse(`	for _, v := range m.{{ .Field }} {
		buf = v.append{{ .Suffix }}(buf)
	}
`)),

	"byte": template.Must(template.New("byte_append").Parse(`	buf = append(buf, m.{{ .Field }})
`)),

	"remaining_bytes": template.Must(template.New("remaining_bytes_append").Parse(`	buf = append(buf, m.{{ .Field }}...)
`)),

	"bool": template.Must(template.New("bool_append").Parse(`	if m.{{ .Field }} {
		buf = append(buf, byte(1))
	} else {
		buf = append(buf, byte(0))
	}
`)),

	"message": template.Must(template.New("message_append").Parse(`	buf = m.{{ .Field }}.append{{ .Suffix }}(buf)
`)),
}

func generate(m message, pkg, methodSuffix string) ([]byte, error) {
	g := generator{
		pkg:          pkg,
		methodSuffix: methodSuffix,
		buf:          bytes.Buffer{},
	}
	err := g.generateHeader()
	if err != nil {
		return nil, err
	}
	err = g.generateAppend(m)
	if err != nil {
		return nil, err
	}
	err = g.generateParse(m)
	if err != nil {
		return nil, err
	}
	return g.format(), nil
}

func (g *generator) generateHeader() error {
	if len(g.pkg) == 0 {
		return errInvalidPackage
	}
	g.printf(`// Code generated by \"protogen %s\"; DO NOT EDIT.

package %s

import (
	"errors"
	"io"

	"github.com/quic-go/quic-go/quicvarint"
)

`, strings.Join(os.Args[1:], " "), g.pkg)
	return nil
}

func (g *generator) generateAppend(m message) error {
	g.printf("func (m *%s) append%s(buf []byte) []byte {\n", m.name, g.methodSuffix)
	for _, f := range m.fields {
		if err := g.emit(appenderTemplates, f); err != nil {
			return err
		}
	}
	g.printf("	return buf\n")
	g.printf("}\n")
	g.printf("\n")
	return nil
}

func (g *generator) printf(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *generator) format() []byte {
	src, err := imports.Process("msg.go", g.buf.Bytes(), nil)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		fmt.Println(g.buf.String())
		panic(err)
	}
	return src
}

func (g *generator) Write(buf []byte) (int, error) {
	return g.buf.Write(buf)
}
