on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest
    name: lint
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: false
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.21.x', '1.22.x' ]
    runs-on: ubuntu-latest
    name: Unit tests (${{ matrix.go }})
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -race ./...
